swagger: '2.0'
info:
  version: '1.0'
  title: "progettois2 "
  description: Our API allow users to fetch many informations about their gym and their progresses
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
# You should put here the URL to your Heroku instance    
host: se2-movies.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    # x-summary: Users collection
    get:
      summary: List all users in the database
      consumes:
      - application/json
      produces:
      - application/json      
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
            example:
              - id: 45
                password: 12345
                name: Mario
                surname: Rossi
                email: example@email.com
                username: Alejoker
                isPt: false
              - id: 46
                password: qwerty
                name: Bruno
                surname: Bianchi
                email: mail@example.com
                username: VonStaben
                isPt: true
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error500'
          
    post:
      description: >-
        You may create a user using this action. It takes a JSON
        object containing the properties of a user.
      summary: Create a new user
      consumes:
      - application/json
      produces:
      - application/json       
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/userRequestPost'
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/user'
        400:
          description: The json in the request doesn't  contain all the required fields or some unrequired fields are present
          schema:
            $ref: '#/definitions/error400'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error500'
    
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
      - name: userId
        in: path
        required: true
        description: The id of the required user
        type : integer
        format: int64
        minimum: 1
      responses: 
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/user'
        404:
          description: The required id was not found
          schema:
            $ref: '#/definitions/error404'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error500'
    delete:
      summary: Delete a user by ID.
      parameters:
      - name: userId
        in: path
        required: true
        description: The id of the required user
        type : integer
        format: int64
        minimum: 1
      responses:
        200:
          description: Successful Response
        404:
          description: The required id was not found
          schema:
            $ref: '#/definitions/error404'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error500'
    put:
      summary: Modify a user by ID.
      description: >-
        You may modify a user using this action. It takes a JSON
        object containing the properties of a user that have to be modified.
      consumes:
      - application/json
      produces:
      - application/json  
      parameters:
      - name: userId
        in: path
        required: true
        description: The id of the required user
        type : integer
        format: int64
        minimum: 1
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/userRequestPut'
           
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/user'
        400:
          description: The json in the request contains some unrequired fields
          schema:
            $ref: '#/definitions/error400'
        404:
          description: The required id was not found
          schema:
            $ref: '#/definitions/error404'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error500'
            
definitions:
  # This is just a simple model for that defines the Primary Key
  # We could reuse this on the rest of our models.
  PK:
    type: object
    properties:
      id:
        type: number
        description: The identifier.
  user:
    title: user
    type: object
    properties:
      id:
         type: integer
         readOnly: true
         description: the id of the user. Read only
      password:
        type: string
        description: the password of the user
      name:
        type: string
        description: the name of the user
      surname:
        type: string
        description: the surname of the user
      email:
        type: string
        description: the email of the user
      username:
        type: string
        description: the username of the user
      isPt:
        type: boolean
        description: indicates if the user is a personal trainer or not
    example:
        id: 46
        password: qwerty
        name: Bruno
        surname: Bianchi
        email: mail@example.com
        username: VonStaben
        isPt: true
  userRequestPost:
    title: user
    type: object
    required: 
      - name
      - password
      - surname
      - username
      - email
      - isPt
    properties:
      password:
        type: string
        description: the password of the user
        
      name:
        type: string
        description: the name of the user
        
      surname:
        type: string
        description: the surname of the user
        
      email:
        
        type: string
        description: the email of the user
        
      username:
        type: string
        description: the username of the user
        
      isPt:
        type: boolean
        description: indicates if the user is a personal trainer or not
        
    example:
        password: qwerty
        name: Bruno
        surname: Bianchi
        email: mail@example.com
        username: VonStaben
        isPt: true
        
  userRequestPut:
    title: user
    type: object
    
    properties:
      password:
        type: string
        description: the password of the user
        
      name:
        type: string
        description: the name of the user
        
      surname:
        type: string
        description: the surname of the user
        
      email:
        
        type: string
        description: the email of the user
        
      username:
        type: string
        description: the username of the user
        
      isPt:
        type: boolean
        description: indicates if the user is a personal trainer or not
        
    example:
        password: qwerty
        name: Bruno
        surname: Bianchi
        email: mail@example.com
        username: VonStaben
        isPt: true
        
  
  error500:
    title: error
    type: object
    properties:
      error: 
        type: string
        description: type of error
    example: 
      error: server error
  error400:
    title: error
    type: object
    properties:
      error: 
        type: string
        description: type of error
    example: 
      error: request bad formed
  error404:
    title: error
    type: object
    properties:
      error: 
        type: string
        description: type of error
    example: 
      error: id not found
      
